### ISSUE TITLE
Missing Talk Category UI

### ISSUE THREAD

**Issue by tomjn** [imath/wordcamp-talks#16]
It's possible to tag a talk when submitting but categories don't show

**Comment by imath** [comment]
??

Weird! Have you tried to register an account here: http://imath-wctalks.pf1.wpserveur.net

because it's possible to have categories

![capture d ecran 2016-12-21 a 23 03 23](https://cloud.githubusercontent.com/assets/1834524/21407902/2a75ef20-c7d2-11e6-9d5c-fb0ae0f4836e.png)

This is the submit form.


![category](https://cloud.githubusercontent.com/assets/1834524/21407958/79bdf64a-c7d2-11e6-9c1c-6e3afbd5f681.png)



And of course, categories are only showed if they are set by the admin. Speakers can only assign

**Comment by tomjn** [comment]
That makes sense, it was on the frontend I didn't see the options
