### ISSUE TITLE
Various side effects since Post Status change

### ISSUE THREAD

**Issue by imath** [imath/wordcamp-talks#34]
- the speaker cannot edit his talk for an hour anymore
- It's not possible to comment anymore > White screen of death
- It's not possible to use the Post navigation anymore.

**Comment by tomjn** [comment]
> the speaker cannot edit his talk for an hour anymore

I'm unaware of this functionality, where is it implemented?

> It's not possible to comment anymore > White screen of death

I'll look into that

> It's not possible to use the Post navigation anymore.

Is this the previous and next post links when viewing an individual proposal?

**Comment by tomjn** [comment]
> It's not possible to comment anymore > White screen of death

It turns out this isn't a WSOD but a deliberate `exit` statement in core:

```
$comment = wp_handle_comment_submission( wp_unslash( $_POST ) );
if ( is_wp_error( $comment ) ) {
	$data = intval( $comment->get_error_data() );
	if ( ! empty( $data ) ) {
		wp_die( '<p>' . $comment->get_error_message() . '</p>', __( 'Comment Submission Failure' ), array( 'response' => $data, 'back_link' => true ) );
	} else {
		exit;
	}
}
```

At some point it does a check if the post is a private or published post, and if it isn't it bails. There are workarounds on Stack Exchange that enable commenting for the WP Admin UI on any post status, but I imagine this will require a filter to check for this and adjust the status accordingly

**Comment by tomjn** [comment]
I'm closing this in favour of #38
