### ISSUE TITLE
Use a specific Comment's type for Raters review

### ISSUE THREAD

**Issue by imath** [imath/wordcamp-talks#39]
I think we should use a different type from `comment` like `talk_review` for comments made by raters during the review period.

It would be easier to isolate them if needed whatever the "transformation" scenario we choose for the "selected talks to sessions" process.

**Comment by tomjn** [comment]
You mean so that we don't end up with a brief period after a session is created when people can view internal comments? My assumption so far has been that a new session post will be created, and the old post would either be trashed or kept as is.

This would allow various things such as creating multiple sessions out of a talk if it spans across several time slots, recreating a session if somebody messes it up, a recovery option if someone accidentally clicks the button, and a clean break from any post meta or baggage that might come along.

**Comment by imath** [comment]
@JJJ suggested to transform selected talks into sessions during our latest chat on slack. In this scenario, using a different comment type can avoid mixing reviews with regular comments possibly created by the other plugin to give feedbacks on sessions by David Bisset & Pirate Dunbhar.

**Comment by jennybeaumont** [comment]
Just FYI, my understanding is that David Bisset is not a part of the talk review project. Worth Pinging Ptah about how they plan to manage comments/feedback and discuss possible conflicts.

**Comment by tomjn** [comment]
I don't think this is an issue if we're creating/copying posts as comments would not be copied over. This is only an issue if we're changing the post type of an existing post in situ, which I've advised against
